### ISSUE TITLE
Unable to use with webpack w/ react-app-rewired

### ISSUE THREAD

**Issue by itseasy21** [grixu/unplugin-clear-testid#1]
Thanks for this awesome lib.

I'm unfortunately not able to use it inside the react-app-rewired config while extending the webpack plugins. When added it ends up with the following error:
```
C:\Workspace\xxxxx\xxxxx\xxxxx\xxxxx\xxxxx\config-overrides.js:12
    require('unplugin-clear-testid/webpack')({
                                            ^
TypeError: require(...) is not a function
    at Object.override [as webpack] (C:\Workspace\xxxxx\xxxxx\xxxxx\xxxxx\xxxxx\config-overrides.js:12:45)
```

The plugins array is:
```
module.exports = function override(config, env) {
  config.plugins = [
    ...config.plugins,
    new ProvidePlugin({
      React: 'react',
      'ReactDOM': 'react-dom',
    }),
    require('unplugin-clear-testid/webpack')({
      attrs: ['data-testid', 'data-cy'],
      testing: process.env.NODE_ENV === 'testing'
    })
  ];
  return rewiredEsbuild()(config, env);
};

```

**Comment by grixu** [comment]
Hi @itseasy21, thanks for the nice words :) Sorry for the delay in response but I'm on vacation now. 

So, let's try to change the way you pass plugin into an array, to this one:

```
require('unplugin-clear-testid').webpack({
      attrs: ['data-testid', 'data-cy'],
      testing: process.env.NODE_ENV === 'testing'
    })
```

If this does not help, please reply with updated error message or if it is possible with minimal error representation in some repo on GitHub which I could fetch & try to fix it myself :)

**Comment by itseasy21** [comment]
Thanks for looking into this, I did try this earlier but still the same error:

```C:\Workspace\eagle\apps\portals\services\tracking-portal\config-overrides.js:11
    require('unplugin-clear-testid').webpack({
                                     ^

TypeError: require(...).webpack is not a function
    at Object.override [as webpack] (C:\Workspace\eagle\apps\portals\services\tracking-portal\config-overrides.js:11:38)
```

Unfortunately, some of the requirements changed in the product where I tried this so won't be needing to add this at the moment, but happy to keep debugging the issue. Will try to get some repo up as soon as I can

**Comment by grixu** [comment]
Hmm, let's try to import the plugin first then add it to the `override` function. It seems like using `require` is not possible inside of it.
